-- Table: comercial.tab_modelo_contrato

-- DROP TABLE comercial.tab_modelo_contrato;

CREATE TABLE comercial.tab_modelo_contrato
(
  cod_modelo_contrato bigserial NOT NULL,
  cod_contrato_tipo_contrato_fk bigint, -- tabela atributo valor
  txt_modelo text,
  CONSTRAINT tab_modelo_contrato_pkey PRIMARY KEY (cod_modelo_contrato),
  CONSTRAINT fk_modelo_contrato FOREIGN KEY (cod_contrato_tipo_contrato_fk)
      REFERENCES public.tab_atributos_valores (cod_atributos_valores) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE comercial.tab_modelo_contrato
  OWNER TO postgres;
COMMENT ON COLUMN comercial.tab_modelo_contrato.cod_contrato_tipo_contrato_fk IS 'tabela atributo valor';


-- Index: comercial.fki_modelo_contrato

-- DROP INDEX comercial.fki_modelo_contrato;

CREATE INDEX fki_modelo_contrato
  ON comercial.tab_modelo_contrato
  USING btree
  (cod_contrato_tipo_contrato_fk);


INSERT INTO comercial.tab_modelo_contrato(
            cod_contrato_tipo_contrato_fk, txt_modelo)
    VALUES (523, $$"<p align="center"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><strong>CONTRATO DE PRESTA&Ccedil;&Atilde;O DE SERVI&Ccedil;OS </strong></span></span></p>
<p align="center"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><strong>PARA CREDENCIMENTO E GEST&Atilde;O DE OBRIGA&Ccedil;&Otilde;ES SCM PERANTE A ANATEL </strong></span></span></p>
<p align="center"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><u><strong>Pacote Flex </strong></u></span></span></p>
<p align="justify"><br /> </p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Pelo presente instrumento particular, </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>SCM ENGENHARIA DE TELECOMUNICA&Ccedil;&Otilde;ES LTDA - ME</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">, empresa com sede em Bras&iacute;lia, no Central 1 Lt 1/12, sala 338, Taguatinga, CEP 72.010-010, no Distrito Federal, inscrita no CNPJ sob o n&ordm; 10.225.044/0001-73, e no Cadastro Estadual sob o n&ordm; 01882121.00-65, neste ato representado por </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Ana Paula Lira Meira</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">, inscrita no CPF n&ordm; 883.079.721.91, Engenheira da Computa&ccedil;&atilde;o, casada, telefone n&ordm; 61 3046-2406, adiante designada CONTRATADA e;</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>XXXXXXXXXXXXXXXX SERVICOS DE INTERNET LTDA &ndash; ME</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">,&nbsp;empresa sediada na _________________, n&ordm; ____, Bairro ________________________, no Munic&iacute;pio de _________________, no Estado _______________, CEP: _________________, inscrita no CNPJ sob o n&ordm; _________________, neste ato representada por </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>___________________________</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">, Solteira, Gerente Financeira, inscrita no CPF sob o n&ordm; ___________________, telefone _____________________, e-mail: </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">________________________________________, doravante denominada CONTRATANTE, declaram que, nesta data, ajustam entre si, de comum acordo e na melhor forma de direito, o presente Contrato de Presta&ccedil;&atilde;o de Servi&ccedil;os de Consultoria T&eacute;cnica para Credenciamento e Gest&atilde;o de Obriga&ccedil;&otilde;es SCM perante a Anatel, que ser&aacute; regido pela legisla&ccedil;&atilde;o vigente e pelas cl&aacute;usulas e condi&ccedil;&otilde;es seguintes:</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">As partes contratantes, ap&oacute;s terem tido conhecimento pr&eacute;vio das especificidades da Proposta Comercial (que faz parte integrante deste contrato), do texto deste instrumento e compreendido o seu sentido e alcance, tem, justo e acordado, o presente contrato de presta&ccedil;&atilde;o de servi&ccedil;os, descrito e caracterizado neste instrumento, ficando entendido que o presente neg&oacute;cio jur&iacute;dico se regular&aacute; pelas cl&aacute;usulas e condi&ccedil;&otilde;es a seguir alinhadas, bem como pelos servi&ccedil;os pormenorizados na Proposta, mutuamente aceitas e outorgadas.</span></span></p>
<p>&nbsp;</p>
<p align="justify"><br /> </p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>CL&Aacute;USULA PRIMEIRA - DA ADES&Atilde;O A ESTE INSTRUMENTO</strong></span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">A ades&atilde;o pelo CONTRATANTE ao presente Contrato efetiva-se alternativamente por meio de quaisquer dos seguintes eventos abaixo:</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">a) Aceite verbal em negocia&ccedil;&atilde;o via telefone;</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">b) Assinatura do CONTRATO;</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">c) Preenchimento de cadastro e aceite&nbsp;&ldquo;on-line&rdquo;.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">d) Pagamento de boleto banc&aacute;rio ou dep&oacute;sito em Conta Corrente da CONTRATADA.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">e) Percep&ccedil;&atilde;o, de qualquer forma, dos servi&ccedil;os objeto do presente Contrato.</span></span></p>
<p align="justify"><br /> </p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>CL&Aacute;USULA SEGUNDA &ndash; DO OBJETO</strong></span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">A CONTRATADA se compromete a prestar consultoria p&oacute;s outorga com o objetivo de cumprir as exig&ecirc;ncias da Anatel ap&oacute;s a obten&ccedil;&atilde;o de autoriza&ccedil;&atilde;o para explora&ccedil;&atilde;o do servi&ccedil;o de comunica&ccedil;&atilde;o multim&iacute;dia (SCM), visando &agrave; qualidade do servi&ccedil;o e desenvolvimento da contratante. </span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>CL&Aacute;USULA TERCEIRA &ndash; DA VIG&Ecirc;NCIA E DO PRAZO DE PERMAN&Ecirc;NCIA M&Iacute;NIMO</strong></span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">O contrato perdurar&aacute; pelo prazo inicial de </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">36 (trinta e seis)</span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> meses, renovando-se automaticamente por igual per&iacute;odo subsequente, exceto se houver pr&eacute;via comunica&ccedil;&atilde;o, por escrito, no prazo de 30 (trinta) dias, do desejo de p&ocirc;r termo ao contrato ao t&eacute;rmino de sua vig&ecirc;ncia.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Par&aacute;grafo Primeiro.</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> O in&iacute;cio da presta&ccedil;&atilde;o dos servi&ccedil;os ora entabulados se consubstanciar&aacute; t&atilde;o logo a CONTRATANTE proceder &agrave; assinatura, reconhecimento de firmas e remessa via correios deste instrumento &agrave; sede da CONTRATADA.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Par&aacute;grafo Segundo. </strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Mediante a assinatura neste instrumento, a CONTRATANTE se compromete a se manter na base de clientes da CONTRATADA pelo per&iacute;odo m&iacute;nimo estipulado no </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><em>caput</em></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> desta cl&aacute;usula e, como contrapartida, recebe a isen&ccedil;&atilde;o da assessoria para obten&ccedil;&atilde;o e manuten&ccedil;&atilde;o do credenciamento perante a Anatel, que possui valor nominal avulso de R$2.500,00 (dois mil e quinhentos reais).</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Par&aacute;grafo Terceiro. </strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Na eventualidade de a CONTRATANTE rescindir este instrumento antes de finda sua vig&ecirc;ncia, al&eacute;m da multa preconizada no item VII.I, dever&aacute; reembolsar &agrave; CONTRATADA todo o descontos que obteve em raz&atilde;o da fideliza&ccedil;&atilde;o. </span></span></p>
<p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>CL&Aacute;USULA QUARTA &ndash; DA ESPECIFICA&Ccedil;&Atilde;O DOS SERVI&Ccedil;OS</strong></span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Os servi&ccedil;os a serem prestados pela CONTRATADA &agrave; CONTRATANTE corresponder&atilde;o &agrave; escolha da &uacute;ltima, a qual, ap&oacute;s an&aacute;lise da Proposta Comercial e confrontando-a com sua capacidade e necessidade, optou por contratar o </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><u><strong>PACOTE FLEX</strong></u></span></span> <span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">e conter&aacute; todos os servi&ccedil;os abaixo delineados:</span></span></p>
<p align="justify">&nbsp;</p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>III.I</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> &ndash; </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Representa&ccedil;&atilde;o junto &agrave; Anatel</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">: a CONTRATADA representar&aacute; a CONTRATANTE perante a Anatel, para prestar esclarecimentos e responder as d&uacute;vidas relacionadas &agrave; explora&ccedil;&atilde;o do Servi&ccedil;o de Comunica&ccedil;&atilde;o Multim&iacute;dia (SCM), bem como acompanhar&aacute; periodicamente a tramita&ccedil;&atilde;o dos processos e, quando necess&aacute;rio, tomar&aacute; as medidas para agilizar seu andamento, inclusive atrav&eacute;s de protocolos e of&iacute;cios. </span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>III.II</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> &ndash; </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Entrevista Inicial: </strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">inquiri&ccedil;&atilde;o ao CONTRATANTE, para o fornecimento de informa&ccedil;&otilde;es e preenchimento de </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><em>check-list</em></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> de inclus&atilde;o, para an&aacute;lise das respostas e orienta&ccedil;&otilde;es iniciais acerca do servi&ccedil;o. </span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>III.III</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> &ndash; </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Sistema de Coleta de Informa&ccedil;&otilde;es (SICI);</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> - As empresas prestadoras de servi&ccedil;os de telecomunica&ccedil;&otilde;es no regime privado devem manter atualizado um banco de dados com informa&ccedil;&otilde;es referentes &agrave; presta&ccedil;&atilde;o de servi&ccedil;os em suas respectivas &aacute;reas de atua&ccedil;&atilde;o (Sistema de Coleta de Informa&ccedil;&otilde;es - SICI), cumprindo &agrave; CONTRATADA colaborar com o preenchimento peri&oacute;dico deste banco, evitando san&ccedil;&otilde;es por parte da ANATEL.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>III.IV</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> &ndash; </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Orienta&ccedil;&otilde;es sobre </strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Taxas e Contribui&ccedil;&otilde;es (FUST/FUNTTEL/CONDENCINE): </strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">A CONTRATADA dever&aacute; verificar sobre quais servi&ccedil;os prestados pela CONTRATANTE dever&atilde;o incidir contribui&ccedil;&otilde;es, tais quais o Fundo de Universaliza&ccedil;&atilde;o das Telecomunica&ccedil;&otilde;es (Fust), o Fundo para o Desenvolvimento Tecnol&oacute;gico das Telecomunica&ccedil;&otilde;es (Funttel) e a Condencine. Al&eacute;m disso, a CONTRATADA assessorar&aacute; a CONTRATANTE, mensalmente, no procedimento de recolhimento do Fust, do Funttel e do Fundo de Fiscaliza&ccedil;&atilde;o das Telecomunica&ccedil;&otilde;es (Fistel), procedendo ao aviso de boletos em aberto perante a Anatel.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>III.V</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> &ndash; </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Calend&aacute;rio de Eventos, cursos, f&oacute;runs e publica&ccedil;&otilde;es:</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> Cumprir&aacute; &agrave; CONTRATADA fornecer periodicamente &agrave; CONTRATANTE um informativo acerca dos eventos relacionados &agrave;s telecomunica&ccedil;&otilde;es e especialmente aos provedores, al&eacute;m de indicar revistas especializadas, com o escopo de propiciar o crescimento e solidifica&ccedil;&atilde;o do Provedor.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>III.VI &ndash; Inova&ccedil;&atilde;o</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">: servi&ccedil;o voltado a divulgar e a orientar a CONTRATANTE em novos processos e projetos na &aacute;rea de telecomunica&ccedil;&otilde;es, objetivando o crescimento e desenvolvimento de sua empresa com solu&ccedil;&otilde;es inovadoras, criativas e com alto valor agregado no mercado, englobando, tamb&eacute;m, a divulga&ccedil;&atilde;o de Editais e Licita&ccedil;&otilde;es vigentes para participa&ccedil;&atilde;o na &aacute;rea de Telecomunica&ccedil;&otilde;es.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>III.VII &ndash; Organiza&ccedil;&atilde;o de Documentos</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">: Orienta&ccedil;&otilde;es sobre a necessidade de obten&ccedil;&atilde;o, guarda e exibi&ccedil;&atilde;o de documentos obrigat&oacute;rios em caso de fiscaliza&ccedil;&atilde;o da Anatel.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>III.VIII &ndash; Sistemas Interativos da Anatel</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">: recomenda&ccedil;&otilde;es e dire&ccedil;&otilde;es sobre a utiliza&ccedil;&atilde;o e registros no sistema FOCUS da Anatel.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>III.IX &ndash; Consultoria Jur&iacute;dica B&aacute;sica</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">: elabora&ccedil;&atilde;o de contratos SCM, Link Dedicado, Perman&ecirc;ncia e Termo de Ades&atilde;o, atualiza&ccedil;&atilde;o dos instrumentos de acordo com modifica&ccedil;&otilde;es legislativas ou normativas, orienta&ccedil;&otilde;es da rescis&atilde;o dos contratos dos provedores com seus usu&aacute;rios finais, indica&ccedil;&atilde;o das medidas jur&iacute;dicas a serem tomadas em caso de procedimentos administrativos na Anatel e divulga&ccedil;&atilde;o de informativos acerca de inova&ccedil;&otilde;es regulat&oacute;rias.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>III.X &ndash; Orienta&ccedil;&otilde;es Cont&aacute;beis B&aacute;sicas:</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> Auxilio sobre requerimento e confec&ccedil;&atilde;o da Nota Fiscal modelo 21, Indica&ccedil;&atilde;o dos CNAE&acute;s espec&iacute;fico para licen&ccedil;a e atividade de SCM e Indica&ccedil;&atilde;o quanto &agrave; filia&ccedil;&atilde;o sindical e o recolhimento das contribui&ccedil;&otilde;es sindicais. </span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>III.XI -</strong></span></span> <span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Auxilio Boletos com usu&aacute;rio final &ndash; </strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">A CONTRATADA auxiliar&aacute; a CONTRATANTE na confec&ccedil;&atilde;o dos boletos banc&aacute;rios a serem emitidos para adimplir a rela&ccedil;&atilde;o jur&iacute;dica entre a prestadora de servi&ccedil;os de telecomunica&ccedil;&otilde;es e seu usu&aacute;rio final, sempre em estrita obedi&ecirc;ncia &agrave;s exig&ecirc;ncias da Anatel.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>III.XII &ndash; Informativo de Situa&ccedil;&atilde;o Financeira perante a Anatel:</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> A CONTRATADA divulgar&aacute; o CONTRATANTE acerca de eventuais d&eacute;bitos em aberto na Anatel e o orientar&aacute; quanto &agrave;s condi&ccedil;&otilde;es de regulariza&ccedil;&atilde;o.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>III.XIII &ndash; Cobran&ccedil;a do CONDENCINE:</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> Aux&iacute;lio na emiss&atilde;o do documento de cobran&ccedil;a do CONDENCINE.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>III.XIV &ndash; Informativo de Altera&ccedil;&otilde;es Administrativas e/ou T&eacute;cnicas:</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> A CONTRATADA atualizar&aacute; o CONTRATANTE acerca de novas exig&ecirc;ncias ou par&acirc;metros da Anatel sobre quest&otilde;es t&eacute;cnicas e administrativas, se responsabilizando, tamb&eacute;m, por elaborar o of&iacute;cio de comunica&ccedil;&atilde;o &agrave; Ag&ecirc;ncia quando sobrevier altera&ccedil;&atilde;o no contrato social do cliente.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>III.XV - Auxilio</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong> inclus&atilde;o ou retirada respons&aacute;vel t&eacute;cnico CREA</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> Cumprir&aacute; &agrave; CONTRATADA guiar a CONTRATANTE nos procedimentos de inclus&atilde;o, modifica&ccedil;&atilde;o ou retirada de respons&aacute;veis t&eacute;cnicos junto ao CREA e &agrave; Anatel.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>III.XVI - Cadastramento de POP junto a Anatel</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">: Isen&ccedil;&atilde;o do custo de projeto mediante o custeio das taxas administrativas (Anatel e CREA), limitado a um laudo mensal n&atilde;o acumulativo.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>III.XVII - Orienta&ccedil;&atilde;o T&eacute;cnica em Licita&ccedil;&atilde;o</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">: Sugest&otilde;es no &acirc;mbito exclusivamente t&eacute;cnico ao CONTRATANTE para norte&aacute;-lo na participa&ccedil;&atilde;o em Licita&ccedil;&otilde;es de Servi&ccedil;os em Telecomunica&ccedil;&otilde;es.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>III.XVIII - 30 Tickets de Call Center Transbordo:</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> O CONTRATADO far&aacute; jus a 30 atendimentos de Call Center receptivo dentro do exerc&iacute;cio mensal, exclusivamente para transbordo, n&atilde;o acumulativos nos meses posteriores.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><u>Orienta&ccedil;&otilde;es Transbordo:</u></span></span></p>
<p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">O CONTRANTE dever&aacute; avisar com 24hrs de anteced&ecirc;ncia que ser&aacute; realizado o transbordo. Caso n&atilde;o seja avisada a transfer&ecirc;ncia, poder&atilde;o ocorrer filas no atendimento;</span></span></p>
<p>&nbsp;</p>
<p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Liga&ccedil;&otilde;es excedentes possuem o custo de R$ 10,00 (dez reais);</span></span></p>
<p>&nbsp;</p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">As liga&ccedil;&otilde;es recebidas pela CONTRATANTE ser&atilde;o transferidas para a CONTRATADA, atrav&eacute;s de sistema voip (voz sobre ip), sendo de obriga&ccedil;&atilde;o da contratante a disponibiliza&ccedil;&atilde;o de um canal voip e uma conex&atilde;o est&aacute;vel de pelo menos 256 kbps durante o fluxo das liga&ccedil;&otilde;es;</span></span></p>
<p align="justify">&nbsp;</p>
<p align="justify"><a name="page2"></a> <span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">A CONTRATADA n&atilde;o se responsabiliza por preju&iacute;zo em detrimento da m&aacute; configura&ccedil;&atilde;o ou m&aacute; qualidade do equipamento da parte CONTRATANTE, bem como a infraestrutura utilizada. Caso necess&aacute;rio, a CONTRATADA poder&aacute; oferecer um equipamento adequado para os atendimentos, com um custo &agrave; parte.</span></span></p>
<p align="justify">&nbsp;</p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">O n&uacute;mero de atendimento (sac) deve ser fornecido pela CONTRATANTE e colocado juntamente ao cadastro para que sejam feitos testes.</span></span></p>
<p align="justify">&nbsp;</p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Este servi&ccedil;o n&atilde;o substitui as outras formas de atendimento e gerenciamento do atendimento da parte CONTRATANTE, o contrato em refer&ecirc;ncia trata-se apenas do atendimento de primeiro n&iacute;vel, abertura de chamados.</span></span></p>
<p>&nbsp;</p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">A CONTRATANTE ter&aacute; acesso ao sistema por login e senha exclusiva, limitado a 03 (tr&ecirc;s) usu&aacute;rios. O custo para usu&aacute;rios adicionais &eacute; de R$ 50,00 (cinquenta reais) </span></span></p>
<p>&nbsp;</p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">&Eacute; obriga&ccedil;&atilde;o da CONTRATANTE fechar os chamados abertos no sistema de gerenciamento da CONTRATADA com as tratativas realizadas. </span></span></p>
<p align="justify"><br /> </p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><em>Par&aacute;grafo &uacute;nico.</em></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> Na hip&oacute;tese de a CONTRATANTE, no curso do contrato entre as partes, desejar a obten&ccedil;&atilde;o da outorga para explora&ccedil;&atilde;o do Servi&ccedil;o de Comunica&ccedil;&atilde;o Multim&iacute;dia, a CONTRATADA o far&aacute; sem qualquer custo adicional, desde que a CONTRATANTE esteja adimplente com todas suas responsabilidades ora aven&ccedil;adas.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>CL&Aacute;USULA QUINTA &ndash; DAS OBRIGA&Ccedil;&Otilde;ES DAS PARTES</strong></span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">IV.I - A CONTRATANTE se responsabiliza pelo envio peri&oacute;dico e tempestivo de todas as informa&ccedil;&otilde;es, documentos e dados necess&aacute;rios para a consecu&ccedil;&atilde;o dos servi&ccedil;os ora contratados, sob pena de, assim n&atilde;o o fazendo, assumir toda e qualquer responsabilidade decorrente desta omiss&atilde;o, desonerando, por conseguinte, completamente a CONTRATADA.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">IV.I.I - Ademais, a CONTRATADA n&atilde;o se responsabilizar&aacute; por inconsist&ecirc;ncia de informa&ccedil;&otilde;es prestadas pela CONTRATANTE, especialmente as relacionadas ao faturamento e declara&ccedil;&otilde;es ao FUST e ao FUNTTEL, ficando pactuado que &eacute; de &uacute;nica, integral e exclusiva responsabilidade da CONTRATANTE proceder com regularidade nas informa&ccedil;&otilde;es transmitidas &agrave; Anatel, sendo, por via obl&iacute;qua, vedado transferir tais obriga&ccedil;&otilde;es &agrave; CONTRATADA.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">IV.II &ndash; Todas as taxas, impostos ou despesas referentes &agrave; execu&ccedil;&atilde;o dos servi&ccedil;os objeto deste instrumento correr&atilde;o por conta exclusiva da CONTRATANTE, cumprindo &agrave; CONTRATADA, neste particular, a confer&ecirc;ncia da exatid&atilde;o de tais incid&ecirc;ncias.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">IV.II.I - A CONTRATANTE arcar&aacute;, ainda, com eventuais custas e despesas, tais quais transporte, hospedagem, alimenta&ccedil;&atilde;o, extra&ccedil;&atilde;o de fotoc&oacute;pias, de autentica&ccedil;&otilde;es e envio de documentos, de expedi&ccedil;&atilde;o de certid&otilde;es e quaisquer outras que decorrerem dos servi&ccedil;os ora contratados, mediante apresenta&ccedil;&atilde;o de demonstrativos anal&iacute;ticos pela CONTRATADA. </span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">IV.III - Fica a CONTRATANTE ciente que n&atilde;o h&aacute; prazo determinado para respostas, of&iacute;cios ou procedimentos, uma vez que a an&aacute;lise dos documentos e a consequente expedi&ccedil;&atilde;o dos resultados s&atilde;o de responsabilidade exclusiva da Ag&ecirc;ncia Nacional de Telecomunica&ccedil;&otilde;es (Anatel). </span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">IV.IV - A CONTRATADA n&atilde;o se responsabilizar&aacute; por qualquer preju&iacute;zo decorrente de falhas da CONTRATANTE relacionadas aos servi&ccedil;os objeto deste instrumento, seja por incorreta execu&ccedil;&atilde;o, entendimento equivocado, neglig&ecirc;ncia, imper&iacute;cia, imprud&ecirc;ncia ou quaisquer outros fatores, n&atilde;o podendo a CONTRATADA, por &oacute;bvio, sofrer quaisquer san&ccedil;&otilde;es ou preju&iacute;zos em virtude de tais ocorr&ecirc;ncias.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">IV.V &ndash; As PARTES s&atilde;o, individualmente, as &uacute;nicas e exclusivas respons&aacute;veis por seus pr&oacute;prios profissionais, do ponto de vista t&eacute;cnico e trabalhista, garantindo suas compet&ecirc;ncias e capacidades, inexistindo qualquer v&iacute;nculo obrigacional al&eacute;m do ora convencionado. </span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>CL&Aacute;USULA SEXTA - DO PRE&Ccedil;O, DA FORMA DE PAGAMENTO E DO REAJUSTE</strong></span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">O pagamento referente ao instrumento ora firmado perfazer&aacute; a import&acirc;ncia total de </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>R$18.329,40 (dezoito mil trezentos e vinte e nove reais e quarenta centavos</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">)</span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">, eis que a CONTRATANTE aderiu ao </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><u><strong>Plano Flex</strong></u></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">, pelo per&iacute;odo estipulado na cl&aacute;usula segunda desta aven&ccedil;a, o qual, por mera liberalidade da CONTRATADA, ser&aacute; adimplido mediante </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>36 (trinta e seis) presta&ccedil;&otilde;es de R$509,15 (quinhentos e nove reais e quinze centavos)</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> cada uma, vencendo a primeira parcela no dia </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><u><strong>30 (trinta) do m&ecirc;s de outubro de 201</strong></u></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><u><strong>5</strong></u></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> e as demais no mesmo dia dos meses subsequentes. </span></span></p>
<p align="justify">&nbsp;</p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Par&aacute;grafo primeiro.</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> No ato de assinatura deste instrumento, a CONTRATADA providenciar&aacute; o envio dos respectivos boletos banc&aacute;rios &agrave; sede da CONTRATANTE, via e-mail e correios.</span></span></p>
<p align="justify">&nbsp;</p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Par&aacute;grafo segundo.</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> Em caso de atraso no adimplemento das parcelas mensais, al&eacute;m de facultada a interrup&ccedil;&atilde;o na presta&ccedil;&atilde;o do servi&ccedil;o, incidir&aacute; multa morat&oacute;ria no importe de 5% (cinco por cento) sobre o valor em aberto, al&eacute;m de juros legais calculados </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><em>pro rata die</em></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> e corre&ccedil;&atilde;o monet&aacute;ria pelo IGP-M, ou por outro &iacute;ndice que eventualmente vier a substitu&iacute;-lo. </span></span></p>
<p align="justify">&nbsp;</p>
<p align="justify"><span style="color: #000000;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Par&aacute;grafo terceiro. </strong></span></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Os valores pactuados no </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><em>caput</em></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> desta cl&aacute;usula, na hip&oacute;tese de renova&ccedil;&atilde;o contratual, sofrer&atilde;o reajuste anual pelo IGP-M, ou por outro &iacute;ndice que eventualmente vier a substitu&iacute;-lo. </span></span></p>
<p align="justify"><br /> </p>
<p align="justify"><span style="color: #000000;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>CL&Aacute;USULA S&Eacute;TIMA &ndash; </strong></span></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>DA CONFIDENCIALIDADE</strong></span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">VI.I. Os servi&ccedil;os e as informa&ccedil;&otilde;es t&eacute;cnicas espec&iacute;ficas utilizadas na consecu&ccedil;&atilde;o dos servi&ccedil;os prestados pela empresa CONTRATADA dever&atilde;o ser utilizados &uacute;nica e exclusivamente para o fim ora estabelecido, motivo pelo qual a CONTRATADA se compromete expressamente, atrav&eacute;s do presente, a tomar todas as precau&ccedil;&otilde;es necess&aacute;rias para salvaguardar o sigilo das mesmas, bem como evitar e prevenir revela&ccedil;&atilde;o a terceiros, n&atilde;o podendo utiliz&aacute;-las para outros projetos que por ventura esteja desenvolvendo, exceto se devidamente autorizado por escrito pela CONTRATANTE.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Par&aacute;grafo &uacute;nico.</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"> As informa&ccedil;&otilde;es t&eacute;cnicas que n&atilde;o poder&atilde;o ser passadas pela CONTRATADA ser&atilde;o aquelas consideradas sigilosas, ou seja, que n&atilde;o estejam protegidas atrav&eacute;s de concess&atilde;o de patente.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">VI.II. Outrossim, a CONTRATADA obriga-se, expressamente, por qualquer motivo ou raz&atilde;o, a n&atilde;o utilizar, divulgar, propagar, reproduzir, explorar, publicar, duplicar, transferir ou revelar, direta ou indiretamente, por si ou atrav&eacute;s de terceiros, quaisquer destas informa&ccedil;&otilde;es. </span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">VI.III. A viola&ccedil;&atilde;o da presente Cl&aacute;usula de Confidencialidade, pelo uso indevido de qualquer informa&ccedil;&atilde;o, sem a devida autoriza&ccedil;&atilde;o, causar&aacute; &agrave; CONTRATANTE danos e preju&iacute;zos irrepar&aacute;veis. Porquanto, uma vez lesada a CONTRATANTE, desde que leg&iacute;tima detentora do direito a tais informa&ccedil;&otilde;es, poder&aacute; tomar todas as medidas judiciais e extrajudiciais, inclusive de car&aacute;ter cautelar ou de antecipa&ccedil;&atilde;o de tutela jurisdicional, que julgar cab&iacute;veis &agrave; defesa de seus direitos, inclusive perdas e danos.</span></span></p>
<p align="justify"><br /> </p>
<p align="justify"><span style="color: #000000;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>CL&Aacute;USULA OITAVA &ndash; DA RESCIS&Atilde;O</strong></span></span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">VII.I - O presente instrumento ser&aacute; rescindido pelo t&eacute;rmino de seu prazo de vig&ecirc;ncia e desinteresse das partes pela prorroga&ccedil;&atilde;o, bem como caso uma das partes descumpra o estabelecido em qualquer uma das cl&aacute;usulas deste contrato, aplicando-se multa de 20% (vinte por cento) sobre o valor restante do contrato &agrave; parte que originou o descumprimento, com vencimento para 5 (cinco) dias &uacute;teis ap&oacute;s a ocorr&ecirc;ncia.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">VII.II &ndash; Conforme aven&ccedil;ado alhures, uma vez que a CONTRATADA rescinda o presente pacto antes de transcorrido integralmente o prazo de 36 (trinta e seis) meses, tamb&eacute;m dever&aacute; ressarcir a CONTRATANTE na exata quantia da isen&ccedil;&atilde;o que obteve em fun&ccedil;&atilde;o da contrata&ccedil;&atilde;o nesta modalidade, qual seja, de R$2.500,00 (dois mil e quinhentos reais), nos moldes do previsto no par&aacute;grafo segundo da cl&aacute;usula segunda desta aven&ccedil;a.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">VII.III - Na hip&oacute;tese de a CONTRATANTE incorrer em atrasos no adimplemento de alguma das parcelas, al&eacute;m das penalidades previstas no Par&aacute;grafo Segundo da Cl&aacute;usula Quinta, persistindo a mora da CONTRATANTE ap&oacute;s 30 (trinta) dias do vencimento de alguma das parcelas, os servi&ccedil;os ser&atilde;o imediatamente suspensos, respondendo a CONTRATANTE junto aos &oacute;rg&atilde;os os quais a CONTRATADA atua pela des&iacute;dia ou falta de continuidade nos servi&ccedil;os at&eacute; ent&atilde;o prestados, al&eacute;m de incidir, a t&iacute;tulo de cl&aacute;usula penal, indeniza&ccedil;&atilde;o &agrave; CONTRATADA na quantia correspondente a uma presta&ccedil;&atilde;o mensal ora ajustada.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">VII.IV - Em qualquer hip&oacute;tese rescis&oacute;ria, salvo em caso de mora da CONTRATANTE, a parte que a desejar deve comunicar a outra por escrito, e com anteced&ecirc;ncia m&iacute;nima de 30 (trinta) dias em rela&ccedil;&atilde;o ao vencimento do pr&oacute;ximo boleto banc&aacute;rio, permanecendo o cumprimento do contrato pelos 30 (trinta) dias posteriores &agrave; comunica&ccedil;&atilde;o, quando se formalizar&aacute; o encerramento do contrato, por interm&eacute;dio de </span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Distrato.</span></span></p>
<p align="justify"><br /> </p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>CL&Aacute;USULA NONA &ndash; DAS DISPOSI&Ccedil;&Otilde;ES GERAIS</strong></span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">VIII.I - Declaram as PARTES que tiveram ampla liberdade quanto &agrave; presente contrata&ccedil;&atilde;o, a qual foi feita em estrita observ&acirc;ncia aos limites do respectivo fim econ&ocirc;mico ou social, pela boa-f&eacute; e/ou pelos bons costumes, levando em considera&ccedil;&atilde;o inclusive que n&atilde;o est&atilde;o em situa&ccedil;&atilde;o de premente necessidade e t&ecirc;m plenas condi&ccedil;&otilde;es de cumprir todas as cl&aacute;usulas e condi&ccedil;&otilde;es que constituem seus direitos e obriga&ccedil;&otilde;es constantes no presente instrumento.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">VIII.II - Todos os termos e condi&ccedil;&otilde;es desta aven&ccedil;a vinculam as PARTES bem como seus sucessores a qualquer t&iacute;tulo. Dessa forma, as PARTES se comprometem a cientificar eventuais sucessores acerca desse instrumento e da obrigatoriedade de sua execu&ccedil;&atilde;o.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">VIII.III - As disposi&ccedil;&otilde;es deste instrumento somente poder&atilde;o ser alteradas mediante acordo escrito entre as partes, atrav&eacute;s de termos aditivos que far&atilde;o parte integrante do contrato, ficando, desde j&aacute;, consignado que atos de toler&acirc;ncia n&atilde;o configurar&atilde;o nova&ccedil;&atilde;o contratual.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">VIII.IV - A CONTRATADA poder&aacute; alterar, modificar ou aditar o presente instrumento, unilateralmente, inclusive no que diz respeito &agrave;s condi&ccedil;&otilde;es dos servi&ccedil;os, atrav&eacute;s de meros comunicados/aditivos, sempre com o objetivo de aprimor&aacute;-lo e/ou adequ&aacute;-lo a novas disposi&ccedil;&otilde;es normativas, as quais se afigurem essenciais para a continuidade da presta&ccedil;&atilde;o de servi&ccedil;os.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">VIII.IV.I &ndash; Considerando que a presta&ccedil;&atilde;o dos servi&ccedil;os ora celebrada deve sempre estar em conson&acirc;ncia com as respectivas normas legais vigentes, advindo sua altera&ccedil;&atilde;o, caber&aacute; contratante adaptar-se &agrave; eventuais mudan&ccedil;as legais/resolut&oacute;rias, que acarretar&atilde;o em exclus&atilde;o ou acr&eacute;scimo de itens ao presente contrato.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">VIII.V - As PARTES reconhecem o correio eletr&ocirc;nico como meio v&aacute;lido, eficaz e suficiente de quaisquer comunica&ccedil;&otilde;es ou avisos concernentes ao presente instrumento.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>CL&Aacute;USULA D&Eacute;CIMA &ndash; DO FORO</strong></span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">As partes elegem o foro da Comarca de Bras&iacute;lia/DF para dirimir quaisquer controv&eacute;rsias oriundas do presente pacto, em detrimento de qualquer outro, por mais especial ou privilegiado que seja.</span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">E por estarem justos e acertados, assinam, na presen&ccedil;a das testemunhas abaixo qualificadas, que a tudo assistem e apostam suas firmas, o presente Contrato em duas vias de igual teor e valor, para que o mesmo surte seus efeitos legais a partir da presente data.</span></span></p>
<p align="justify"><a name="_GoBack"></a> <span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Bras&iacute;lia, ___ de _____________ de 201_.</span></span></p>
<p align="center"><br /> </p>
<p align="center"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>_______________________________________________________</strong></span></span></p>
<p align="center"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>XXXXXXXXXXXXXXXXXX SERVICOS DE INTERNET LTDA &ndash; ME</strong></span></span></p>
<p align="center"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>CONTRATANTE</strong></span></span></p>
<p align="center"><br /> </p>
<p align="center"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>_______________________________________________________</strong></span></span></p>
<p align="center"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>SCM ENGENHARIA DE TELECOMUNICA&Ccedil;&Otilde;ES LTDA - ME </strong></span></span></p>
<p align="center"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>CONTRATADA</strong></span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>1</strong></span></span><sup><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><u><strong>a</strong></u></span></span></sup><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong> Testemunha</strong></span></span></p>
<p align="justify"><br /> </p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>2</strong></span></span><sup><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><u><strong>a</strong></u></span></span></sup><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong> Testemunha</strong></span></span></p>"$$);



ALTER TABLE comercial.tab_socios ADD COLUMN representante_comercial boolean;
COMMENT ON COLUMN comercial.tab_socios.representante_comercial IS 'Responsável pela assinatura do contrato';
